name: Build and test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with testing
      run: ./gradlew --info --stacktrace check
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: tests
        path: build/reports/tests/test
    - name: JaCoCo test report
      if: success()
      run: ./gradlew jacocoTestReport
    - uses: actions/upload-artifact@v1
      if: success()
      with:
        name: jacoco
        path: build/reports/jacoco/test
